// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YachtWorld.Infrastructure.Data;

#nullable disable

namespace YachtWorld.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221110193241_AddDestinationToYacht")]
    partial class AddDestinationToYacht
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05ff3575-52f9-4566-a4e6-96746446f8af",
                            Email = "yachtBroker@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "YACHTBROKER@MAIL.COM",
                            NormalizedUserName = "YACHTBROKER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEb0O2z8Ivrou1UkfWRW5b0Rr6ApoVF0o3UCk3scXtmCGSH6l630QJxXjMhrFc9swg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb8868b9-be80-428c-8684-7f061c9e38a9",
                            TwoFactorEnabled = false,
                            UserName = "yachtBroker@mail.com"
                        },
                        new
                        {
                            Id = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e91de83-ad05-4087-b755-8c9ff2268bb1",
                            Email = "guest@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST@MAIL.COM",
                            NormalizedUserName = "GUEST@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKF66heXhKxPlx5dO+Frcg8d0hIbUfiNeMES4qv39rCMuyuE059ogse4FrjFZ5hiVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56ed46c2-5a03-4747-8b23-6589567961c2",
                            TwoFactorEnabled = false,
                            UserName = "guest@mail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Green-Yachts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yacht-With-Captain"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Large"
                        });
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MainAttraction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MainAttraction = "Cannes Film Festival",
                            Name = "Mediterannean"
                        },
                        new
                        {
                            Id = 2,
                            MainAttraction = "Tropical Climate",
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 3,
                            MainAttraction = "Swim by a Waterfall",
                            Name = "Australasia"
                        },
                        new
                        {
                            Id = 4,
                            MainAttraction = "Northern Lights",
                            Name = "Northern Europe"
                        },
                        new
                        {
                            Id = 5,
                            MainAttraction = "Flourishing Nature",
                            Name = "South Pacific"
                        });
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.Shipyard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EstablishedIn")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Shipyards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstablishedIn = 1980,
                            Location = "New Zealand",
                            Name = "Alloy Yachts"
                        },
                        new
                        {
                            Id = 2,
                            EstablishedIn = 1918,
                            Location = "Germany",
                            Name = "Amels Yachts"
                        },
                        new
                        {
                            Id = 3,
                            EstablishedIn = 1969,
                            Location = "Italy",
                            Name = "Azimut Yachts"
                        },
                        new
                        {
                            Id = 4,
                            EstablishedIn = 1854,
                            Location = "Port of Genova",
                            Name = "Baglietto"
                        },
                        new
                        {
                            Id = 5,
                            EstablishedIn = 1873,
                            Location = "Italy",
                            Name = "Benetti Yachts"
                        },
                        new
                        {
                            Id = 6,
                            EstablishedIn = 1863,
                            Location = "USA",
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Vancouver Washington",
                            Name = "Cristensen Yachts"
                        },
                        new
                        {
                            Id = 8,
                            EstablishedIn = 1825,
                            Location = "Italy",
                            Name = "Codecasa Yachts"
                        },
                        new
                        {
                            Id = 9,
                            EstablishedIn = 1919,
                            Location = "Holland",
                            Name = "Hakvoort Yachts"
                        },
                        new
                        {
                            Id = 10,
                            EstablishedIn = 1960,
                            Location = "Brazil",
                            Name = "Inace"
                        });
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.Yacht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CrewMembers")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Engines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Generators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceForRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("money");

                    b.Property<string>("SailorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ShipyardId")
                        .HasColumnType("int");

                    b.Property<int>("StateRooms")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YachtBrokerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("SailorId");

                    b.HasIndex("ShipyardId");

                    b.HasIndex("YachtBrokerId");

                    b.ToTable("Yachts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CrewMembers = 33,
                            Description = "Delivered in 2020 and one of the finest jewels delivered by Benetti, 107m / 351' Frodo is a charter yacht of choice in the 100m+/300'+ range. Built and designed by Benetti to discover every corner of the world, her striking lines are matched with an unrivaled level of luxury on all decks. Powered by an unusual Rolls-Royce hybrid-electric propulsion, Frodo ensures wonderful fuel efficiency and a long cruising range, making her eco-friendly with a cruising speed of 16 knots, and 18.5 knots top speed.",
                            DestinationId = 1,
                            Generators = "3 X Caterpillar",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Frodo.png",
                            Length = "107 Metres",
                            MaxSpeed = "18.5 Knots",
                            PriceForRent = 1800000.00m,
                            SailorId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e",
                            ShipyardId = 1,
                            StateRooms = 8,
                            Title = "Frodo",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CrewMembers = 36,
                            Description = "Aragorn is one of the world's largest and most impressive charter yachts, ideal for entertaining on a grand scale. She boasts many special features including a spa, a gym, a cinema and vast deck spaces. Her interior is opulent and grand and she features not one but two Jacuzzis. Accommodating 36 guests in eighteen staterooms she offers a large group or several small groups the chance for the experience of a lifetime on the West Mediterranean.",
                            DestinationId = 2,
                            Engines = "2 X Caterpillar",
                            Generators = "3 X Caterpillar",
                            Guests = 36,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Aragorn.png",
                            Length = "91.4 Metres",
                            MaxSpeed = "15 Knots",
                            PriceForRent = 645000.00m,
                            ShipyardId = 2,
                            StateRooms = 18,
                            Title = "Aragorn",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CrewMembers = 34,
                            Description = "One of the world’s fastest explorer yachts at 23 knots, Samwise combines adventure yacht capabilities with a superyacht finish. Featuring a helideck suitable for an AW109 or similar, plus a crane with 15M (49’) reach ideal for launching the array of tenders and toys on board, she offers unlimited possibilities.",
                            DestinationId = 3,
                            Engines = "2 X Caterpillar",
                            Generators = "3 X Caterpillar",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Samwise.png",
                            Length = "85.1 Metres",
                            MaxSpeed = "17.5 Knots",
                            PriceForRent = 1000000.00m,
                            ShipyardId = 7,
                            StateRooms = 8,
                            Title = "Samwise",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CrewMembers = 26,
                            Description = "Meriadoc is a multi-award-winning, feature-packed explorer yacht equipped to provide the ultimate charter experience. The 85-metre superyacht for charter offers the best of both worlds, made to entertain and explore the beauty the world has to offer. Delivered by AKYACHT in Summer 2021, she brings together Michael Leach Design and H2 Yacht Design.",
                            DestinationId = 4,
                            Engines = "2 X Caterpillar",
                            Generators = "4 X Caterpillar",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Meriadoc.png",
                            Length = "85.1 Metres",
                            MaxSpeed = "16 Knots",
                            PriceForRent = 934700.00m,
                            ShipyardId = 5,
                            StateRooms = 6,
                            Title = "Meriadoc",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CrewMembers = 28,
                            Description = "Peregrin was built for pure fun and adventure. With a 7,640 nautical mile range and equipped with all the latest toys, she offers pure unadulterated adventure, thrills and fun with all the luxuries you would come to expect of a superyacht from world-class cuisine to a dedicated spa centre, all whilst cruising the world’s remotest oceans. Not for charter to US residents while in US waters.",
                            DestinationId = 5,
                            Engines = "2 X Smit-Man",
                            Generators = "3 X John Deere",
                            Guests = 28,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Peregrin.png",
                            Length = "77.4 Metres",
                            MaxSpeed = "12 Knots",
                            PriceForRent = 604700.00m,
                            ShipyardId = 9,
                            StateRooms = 11,
                            Title = "Peregrin",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CrewMembers = 21,
                            Description = "Enhance your Legolas experience: watch here the Chief Stewardess preparing the yacht's cocktail signature HOT WHEELS, and join the Captain here for a complete walkthrough. A certified family-friendly motor yacht for charter, 76m/249’ Legolas is undoubtedly one of the most acclaimed vessels in her range. Seven decks of outstanding features are spread over a volume of nearly 2,000GT . Legolas is operated by an Owner who has been meticulous in her maintenance and upgrades.",
                            DestinationId = 1,
                            Engines = "2 X MTU",
                            Generators = "3 X Caterpillar",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Legolas.png",
                            Length = "75.5 Metres",
                            MaxSpeed = "18 Knots",
                            PriceForRent = 836300.00m,
                            ShipyardId = 4,
                            StateRooms = 6,
                            Title = "Legolas",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CrewMembers = 19,
                            Description = "Having undergone an interior refit in 2018, 73M Lurssen yacht for charter Gimli is everything you would expect from such a renowned shipyard and more. Boasting magnificent spaces both inside and out she offers all the features of luxury life on a superyacht, including huge entertainment spaces, the very latest amenities and incredible accommodation.",
                            DestinationId = 2,
                            Engines = "2 X Caterpillar",
                            Generators = "2 X Caterpillar",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Gimli.png",
                            Length = "73 Metres",
                            MaxSpeed = "16 Knots",
                            PriceForRent = 585400.00m,
                            ShipyardId = 10,
                            StateRooms = 7,
                            Title = "Gimli",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CrewMembers = 30,
                            Description = "Smeagol is a recently refit 72M superyacht available for charter in the Mediterranean, the Balearics, Croatia, the Arabian Gulf, Indian Ocean and the Red Sea. She accommodates up to 28 guests in14 staterooms and boasts special features such as a Jacuzzi. Her spacious decks provide the ideal situation for relaxing with friends or family and taking in the scenery of the surrounding area.",
                            DestinationId = 3,
                            Engines = "2 X MTU",
                            Generators = "3 X MAN",
                            Guests = 30,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Smeagol.png",
                            Length = "72 Metres",
                            MaxSpeed = "16.2 Knots",
                            PriceForRent = 559000.00m,
                            ShipyardId = 3,
                            StateRooms = 16,
                            Title = "Smeagol",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CrewMembers = 19,
                            Description = "Boromir offers the ultimate charter experience. She accommodates up to 26 guests in 13 beautiful staterooms, features a spa on board, in addition to a plethora of toys. Her luxurious interior décor and incredible facilities create the ideal charter yacht for large families or corporate events. Not for charter to US residents while in US waters.",
                            DestinationId = 4,
                            Engines = "1 X Caterpillar",
                            Generators = "2 X John Deere",
                            Guests = 28,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Boromir.png",
                            Length = "69.65 Metres",
                            MaxSpeed = "13 Knots",
                            PriceForRent = 492900.00m,
                            ShipyardId = 6,
                            StateRooms = 13,
                            Title = "Boromir",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CrewMembers = 13,
                            Description = "Gandalf, the 54.3M Amels superyacht for charter, is a world cruiser designed for free spirits that harmoniously combines zen and adventure. She accommodates 11 guests in five staterooms and is available in the Caribbean and Central America. She boasts a contemporary interior and spacious decks, as well as an impressive range of water toys for guests' recreational enjoyment.",
                            DestinationId = 5,
                            Engines = "2 X MTU",
                            Generators = "3 X Northern Lights",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Gandalf.png",
                            Length = "54.3 Metres",
                            MaxSpeed = "15.5 Knots",
                            PriceForRent = 299900.00m,
                            ShipyardId = 8,
                            StateRooms = 5,
                            Title = "Gandalf",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CrewMembers = 14,
                            Description = "With her traditional lines and Feadship pedigree Saruman epitomises classic superyacht charm, yet delve a little deeper  and you find interiors and amenities at the highest levels of modern luxury. Saruman is committed to lowering its impact on the environment by making a conscious effort to reduce  its carbon footprint.",
                            DestinationId = 1,
                            Engines = "2 X Caterpillar",
                            Generators = "2 X Northern Lights",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Saruman.png",
                            Length = "53.1 Metres",
                            MaxSpeed = "16 Knots",
                            PriceForRent = 203300.00m,
                            ShipyardId = 9,
                            StateRooms = 8,
                            Title = "Saruman",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CrewMembers = 10,
                            Description = "Sauron is a beautiful 52m yacht for charter with accommodation for 12 guests in six comfortable staterooms. Spacious and classic in style, Sauron boasts a hot tub, sports bar, vast alfresco dining area and an abundant array of water toys. Her large party deck is ideal for entertaining.",
                            DestinationId = 2,
                            Engines = "2 X Cummins",
                            Generators = "3 X Northern Lights",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Sauron.png",
                            Length = "52.4 Metres",
                            MaxSpeed = "15 Knots",
                            PriceForRent = 172100.00m,
                            ShipyardId = 7,
                            StateRooms = 6,
                            Title = "Sauron",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CrewMembers = 11,
                            Description = "Smaug is a highly pedigreed yacht, blending modern and classic styles.  Accommodations include five spacious staterooms with three staterooms with king beds and two staterooms with queen beds.  Two of the kings convert to twin beds with two Pullman berths in each of these staterooms. Additional amenities include a wide assortment of water toys, exercise equipment, large tender, shade for alfresco dining, multiple areas for sunbathing and a Jacuzzi.",
                            DestinationId = 3,
                            Engines = "2 X Caterpillar",
                            Generators = "2 X Northern Lights",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Smaug.png",
                            Length = "51.1 Metres",
                            MaxSpeed = "15 Knots",
                            PriceForRent = 249100.00m,
                            ShipyardId = 3,
                            StateRooms = 5,
                            Title = "Smaug",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CrewMembers = 18,
                            Description = "Theoden is the ultimate platform for adventures and exploration around the stunning, remote waters of Indonesia and Asia. A traditional Indonesian Phinisi design launched in 2014, she offers stable and comfortable cruising with no compromise to luxury. Sleeping up to 14 guests in seven spacious and well-appointed staterooms, she features spacious outdoor decks for large groups of friends and families to enjoy while taking in the view.",
                            DestinationId = 4,
                            Engines = "1 X Yanmar",
                            Generators = "2 X Northern Lights",
                            Guests = 50,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Theoden.png",
                            Length = "51 Metres",
                            MaxSpeed = "12 Knots",
                            PriceForRent = 120000.00m,
                            ShipyardId = 1,
                            StateRooms = 7,
                            Title = "Theoden",
                            YachtBrokerId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CrewMembers = 14,
                            Description = "Highly custom designed, with an unmissable metallic blue hull and a sleek silhouette inspired by a modern jet fighter, Elrond combines stunning spaces with the latest technology and boasts a top speed of 25 knots. Featuring a striking open-plan contemporary interior and an award winning exterior, she is ideal for entertaining.",
                            DestinationId = 5,
                            Engines = "2 X MTU",
                            Guests = 12,
                            ImageUrl = "C:\\Users\\Genko\\source\\repos\\YachtWorld\\YachtWorld\\wwwroot\\yachtImages\\Elrond.png",
                            Length = "51 Metres",
                            MaxSpeed = "25 Knots",
                            PriceForRent = 284600.00m,
                            ShipyardId = 10,
                            StateRooms = 8,
                            Title = "Elrond",
                            YachtBrokerId = 1
                        });
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.YachtBroker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("YachtBrokers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "yachtBroker@mail.com",
                            UserId = "dea12856-c198-4129-b3f3-b893d8395082"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.Yacht", b =>
                {
                    b.HasOne("YachtWorld.Infrastructure.Data.Category", "Category")
                        .WithMany("Yachts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YachtWorld.Infrastructure.Data.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Sailor")
                        .WithMany()
                        .HasForeignKey("SailorId");

                    b.HasOne("YachtWorld.Infrastructure.Data.Shipyard", "Shipyard")
                        .WithMany("Yachts")
                        .HasForeignKey("ShipyardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YachtWorld.Infrastructure.Data.YachtBroker", "YachtBroker")
                        .WithMany()
                        .HasForeignKey("YachtBrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");

                    b.Navigation("Sailor");

                    b.Navigation("Shipyard");

                    b.Navigation("YachtBroker");
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.YachtBroker", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.Category", b =>
                {
                    b.Navigation("Yachts");
                });

            modelBuilder.Entity("YachtWorld.Infrastructure.Data.Shipyard", b =>
                {
                    b.Navigation("Yachts");
                });
#pragma warning restore 612, 618
        }
    }
}
